/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class MongoClient {
  /**
   * Connect to MongoDB. `options` is an optional JSON string with pool/timeout
   * config: `{ maxPoolSize, minPoolSize, connectTimeoutMs,
   * serverSelectionTimeoutMs, appName }`. The driver already pools connections;
   * these expose the knobs.
   */
  static connect(uri: string, options?: string | undefined | null): Promise<MongoClient>
  /**
   * Terminate background workers and close connections. Call before process
   * exit: otherwise the driver's topology-monitor tasks keep the runtime
   * alive and Node will not exit. `immediate(true)` does not wait for live
   * cursor handles (acceptable at teardown).
   */
  close(): Promise<void>
  /** Eager find: returns one JSON string per document (Phase 3 path). */
  find(db: string, coll: string, filterJson: string, optsJson: string): Promise<Array<string>>
  /**
   * Lazy find (Phase 4): returns `RawDoc` handles holding raw bytes. No values
   * are parsed until JS reads a field, so the event loop is not blocked by a
   * deserialize burst on return.
   */
  findLazy(db: string, coll: string, filterJson: string, optsJson: string): Promise<Array<RawDoc>>
  /**
   * Streaming lazy find (Phase 4): returns a `FindCursor`. Pull batches with
   * `next_batch()` and process+drop each before the next, so peak live memory
   * is one batch and GC jitter under concurrency stays low.
   */
  findCursor(db: string, coll: string, filterJson: string, optsJson: string): Promise<FindCursor>
}
export declare class FindCursor {
  /**
   * Next batch of lazy `RawDoc` handles, or `null` when exhausted.
   * Awaiting this is a real loop yield point, so timers/IO run between batches.
   */
  nextBatch(): Promise<Array<RawDoc> | null>
}
/** A lazily-parsed MongoDB document backed by raw BSON bytes. */
export declare class RawDoc {
  /** Parse and return a single field. `undefined` if absent. */
  getField(name: string): unknown
  /** Full parse into a plain JS object (escape hatch for spread/JSON.stringify). */
  toObject(): object
  /** Field names without parsing any values. */
  keys(): Array<string>
}
